# Generated by Django 3.2.13 on 2022-05-07 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
            ],
            options={
                'verbose_name': 'lecture',
                'verbose_name_plural': 'lectures',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/images/teacher_image', verbose_name='image')),
            ],
            options={
                'verbose_name': 'teacher',
                'verbose_name_plural': 'teachers',
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
            ],
            options={
                'verbose_name': 'university',
                'verbose_name_plural': 'universities',
            },
        ),
        migrations.CreateModel(
            name='Present',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presents.lecture', verbose_name='lecture')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presents.teacher', verbose_name='teacher')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presents.university', verbose_name='university')),
            ],
            options={
                'verbose_name': 'presenting lesson',
                'verbose_name_plural': 'lesson presentations',
            },
        ),
    ]
