# Generated by Django 3.2.13 on 2022-07-06 14:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registrar', models.CharField(max_length=200, verbose_name='registrant')),
                ('present', models.CharField(max_length=200, verbose_name='presenting lesson')),
                ('rate', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='rate')),
                ('comment', models.TextField(verbose_name='comment')),
            ],
            options={
                'verbose_name': 'assessment',
                'verbose_name_plural': 'assessments',
            },
        ),
    ]
