# Generated by Django 3.2.13 on 2022-05-07 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BadWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=300, unique=True, verbose_name='word')),
            ],
            options={
                'verbose_name': 'bad word',
                'verbose_name_plural': 'bad words',
            },
        ),
    ]
